replicaCount: 1
restartPolicy: Never

image:
  repository: pepakriz/gitlab-merger-bot
  tag: v2.0.0-beta1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 150m
    memory: 192Mi

annotations: {}
labels: {}
nodeSelector: {}
tolerations: []
podAnnotations: {}
env: {}

ingress:
  enabled: false
  routePrefix: "/"
  annotations: {}
  labels: {}
  hosts: []
  paths: []
  tls: []

service:
  annotations: {}
  labels: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  nodePort: "30044"
  port: "4000"
  targetPort: "4000"

settings:
  gitlabUrl: "https://gitlab.com"
  authToken: ""
  sentryDsn: ""
  ciCheckInterval: 10
  mrCheckInterval: 20
  removeBranchAfterMerge: true
  squashMergeRequest: true
  autorunManualBlockingJobs: true
  skipSquashingLabel: ""
  highPriorityLabel: ""
  httpServerEnable: false
  httpServerPort: 4000
  webHookToken: ""
