replicaCount: 1
restartPolicy: Never

image:
  repository: docker.pkg.github.com/pepakriz/gitlab-merger-bot/gitlab-merger-bot
  tag: v2.0.0-beta2
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 150m
    memory: 192Mi

annotations: {}
labels: {}
nodeSelector: {}
tolerations: []
podAnnotations: {}
env: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - chart-example.local
  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000
  nodePort: 30044
  annotations: {}
  labels: {}
  portName: service
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

settings:
  gitlabUrl: "https://gitlab.com"
  authToken: ""
  sentryDsn: ""
  ciCheckInterval: 10
  mrCheckInterval: 20
  removeBranchAfterMerge: true
  squashMergeRequest: true
  autorunManualBlockingJobs: true
  skipSquashingLabel: ""
  highPriorityLabel: ""
  httpServerEnable: false
  httpServerPort: 4000
  webHookToken: ""
