replicaCount: 1
restartPolicy: Never

image:
  repository: pepakriz/gitlab-merger-bot
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 64Mi

annotations: {}
labels: {}
nodeSelector: {}
tolerations: []
podAnnotations: {}

settings:
  gitlabUrl: "https://gitlab.com"
  authToken: ""
  sentryDsn: ""
  ciCheckInterval: 10
  mrCheckInterval: 20
  autorunManualBlockingJobs: true
  skipSquashingLabel: ""
  hiPriorityLabel: ""
