name: tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: EditorConfig Lint
        uses: docker://mstruebing/editorconfig-checker:2.0.3

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn run check:cs

      - name: Check TS types
        run: yarn run check:types

      - name: Test
        run: yarn run check:tests
